name: Trigger Azure Chaos Studio Experiment(AZ CLI)

on:
  workflow_dispatch:
    

jobs:
  trigger-chaos-experiment:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}

    - name: Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az rest --method post --url ${{ secrets.AZURE_CHAOS_STUDIO_API_URL }}
