name: Trigger Azure Chaos Studio Experiment

on:
  workflow_dispatch:
    

jobs:
  trigger-chaos-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Chaos Experiment
        env:
          AZURE_CHAOS_STUDIO_API_URL: ${{ secrets.AZURE_CHAOS_STUDIO_API_URL }}
          AZURE_CHAOS_STUDIO_API_KEY: ${{ secrets.AZURE_CHAOS_STUDIO_API_KEY }}
          EXPERIMENT_ID: "ChaosStudioExperiment"  # Replace with your experiment ID
        shell: pwsh
        run: |
          # Run the PowerShell script to trigger the experiment
          $Headers = @{
              "Authorization" = "Bearer $env:AZURE_CHAOS_STUDIO_API_KEY"
              "Content-Type" = "application/json; charset=utf-8"
          }

          $response = Invoke-RestMethod -Uri $env:AZURE_CHAOS_STUDIO_API_URL -Method Post -Headers $Headers

          # Check the response for success
          if ($($response.name) -eq $env:EXPERIMENT_ID) {
              Write-Output "Experiment triggered successfully"
          } else {
              Write-Error "Failed to trigger experiment. Response: $($response.name), was looking for $env:EXPERIMENT_ID"
              exit 1
          }
