name: Run After Two Approvals
on:
  pull_request_review:
    types: [submitted]

jobs:

  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      
  check_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check Approval Count
        id: approval_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          APPROVALS=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            --jq '[.[] | select(.state=="APPROVED")] | length')
          echo "Number of approvals: $APPROVALS"
          if [ "$APPROVALS" -lt 1 ]; then
            echo "Not enough approvals, exiting."
            exit 1
          fi

      - name: Run Action After One Approval
        if: steps.approval_check.outputs.APPROVALS == 1
        run: |
          if [ -d ".devcontainer" ]; then
            echo ".devcontainer folder found. Deleting..."
            rm -rf .devcontainer
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Deleted .devcontainer folder"
            git push
          else
            echo ".devcontainer folder not found. Skipping."
          fi
