name: Create a Repository

on:
  workflow_dispatch:  # Allows manually triggering the workflow

permissions:
  repository-projects: write
  
jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Create a New Repository
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/user/repos \
          -d '{"name": "CodespacesDemoRepo", "private": false}'
