# This is a basic workflow to help you get started with Actions

name: OIDC With Key Vault

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  KeyVault_Demo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      keyvaultName: AHCSAIACDemo
      secretName: GitHubDemo
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Logging in to Azure with OIDC
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
          
      - name: 'Access Key Vault Secret'
        id: GetKeyVaultSecret
        run: |
          value=$(az keyvault secret show --name $secretName --vault-name $keyvaultName --query value --output tsv)
          echo "SecretValue=$value" >> $GITHUB_OUTPUT
          
      - name: 'Using the secret'
        run: |
          echo "The secret is ${{ steps.GetKeyVaultSecret.outputs.SecretValue }}"
